### ISSUE TITLE
Frogging other FoLiA tags then <s>

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/frog#30]
https://github.com/JessedeDoes This might be of interest for you too!?

When frogging FoLiA documents, we currently only examine Sentences. Which always seemed to make sense. But there are other FoLiA tags bearing text, like  \<head\> and \<note\> . 

Is it desirable to add an option to Frog to also work on those tags? For Instance the Meertens institute seems to have a need to look deeper into the \<head\> nodes. 

Attention: This would also mean a major change in FoLiA itself.!
\<head\> and \<note\> cannot be annotated at the moment.
Especially for \<head\> I wonder if this is correct.

**Comment by proycon** [comment]
The problem is frogging ``note/t`` and ``head/t`` I assume? If there's a ``node//s/t`` or ``head//s/t`` it should already work I reckon? I don't see what would change in FoLiA itself in any case though. Examining anything other than sentences is indeed a bit strange considering the whole thing is trained on sentences, but I guess allowing users to explicitly mention tags that could be treated as sentences (e.g. note/head) is a good idea.

**Comment by kosloot** [comment]
Well: Annotations may not directly be added to \<head\> nor \<note\>, so that IS a problem for FoLiA at the moment.

**Comment by proycon** [comment]
Not? That would be strange indeed. But it should work already I think: https://github.com/proycon/folia/blob/master/schemas/folia.yml#L336   (and more inherited from ``AbstractStructureElement``)

**Comment by martinreynaert** [comment]
Not sure at all this is at all possible...

But should the user not be able to declare text in elements such as 'head' or 'note' as text, so that the tools recognize this as such and annotate accordingly?

This would allow the user to declare 'head' but not 'note' (or indeed vice versa should need be) as text and have it annotated. 

My 2 cents, for now.

M.

**Comment by proycon** [comment]
I think the conclusion is that this is not a Frog issue, but an ucto issue; Frog is right just to look at ``s``. It's the task of ucto to provide ``s`` (sentence detection) and ``w`` (tokenisation) on any FoLiA structure element that can hold them (e.g. has them as ``ACCEPTED_DATA``) and that does not already have deeper structure elements with text layers (``t``).

**Comment by kosloot** [comment]
added as https://github.com/LanguageMachines/ucto/issues/23

**Comment by kosloot** [comment]
Ok, and ucto does what needs to be done, but assumes that the text content is correct.
This is a.o. dependent on https://github.com/proycon/folia/issues/24
to summarize:
The textcontent of a Structure Element is  a composition of the textcontents of the underlying elements (if present)

It is not the task of Frog or Ucto to enforce this.
